common/libs/VkCodecUtils/ProgramConfig.h
As h26x, the av1 codec should be able to be passed to the cli.
=> ProgramConfig: add av1 decode operation

vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfig.cpp
The warning was printed many times while testing with the Vulkan CTS. Since --testOutOfOrderRecording is being passed, it's obvious that the intention is to use it "for testing", therefore the warning is fairly intrusive.
=> Only show warning when testing in verbose mode

common/libs/VkCodecUtils/VulkanFrame.cpp, common/libs/VkCodecUtils/VulkanVideoUtils.cpp, common/libs/VkCodecUtils/VulkanVideoUtils.h
RecordCommandBuffer should use its own member values instead of passing it through its API.
Avoid vars shadowing detected by CTS
Fixes #19
=> VulkanPerDrawContext::RecordCommandBuffer: use member vars

common/libs/VkCodecUtils/DecoderConfig.h
As there is a flag to enable y4m in the decoder config, the default value should be false and enabled by the flag on demand.
=> DecoderConfig: y4m should be off by default

vk_video_decoder/libs/VkVideoDecoder/VkVideoDecoder.cpp, vk_video_decoder/libs/VulkanVideoFrameBuffer/VulkanVideoFrameBuffer.cpp, vk_video_decoder/libs/VulkanVideoFrameBuffer/VulkanVideoFrameBuffer.h
This patch allows to fix the decode process without presentation.
Fixing fluster issue in #10
=> use correct baseArrayLayer for the subresource in optimal to linear image copy

common/libs/VkCodecUtils/DecoderConfig.h, vk_video_decoder/demos/vk-video-dec/Main.cpp, vk_video_decoder/test/vulkan-video-dec/Main.cpp, vk_video_decoder/test/vulkan-video-simple-dec/Main.cpp
By default, if FFmpeg is present, the stream
demuxer should be enabled.
=> DecoderConfig: enable stream demuxing

common/libs/VkCodecUtils/VulkanFilterYuvCompute.cpp
Disable the computer shader log as it is displayed by CTS AV1 encode tests
=> log: disable shaders dump

common/libs/VkCodecUtils/VulkanFilterYuvCompute.cpp
The push constants size in the descriptor is too small compared to the size in the shader.
=> Fix YUV filter push constant size

vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoder.cpp, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderAV1.cpp
For higher image resolutions and bitrates, the fixed 2MB buffer size is inadequate. To handle the worst-case scenario, ensure the bitstream size is the same as the input image size.
https://github.com/nvpro-samples/vk_video_samples/pull/127
=> Set the bitstream buffer size to match the input image size. Cherry picked from NVPro

common/libs/VkShell/Shell.cpp, common/libs/VkShell/Shell.h
Create enough back buffers
according to the caps of the device.
ANV needs more back buffers than NVIDIA driver.
=> Shell: create backBuffer after SwapChain

common/libs/VkCodecUtils/VulkanVideoSession.h
AV1 decoding on ANV requires almost 40 video memories.
H265 encoding requires at least 10 video memories.
See https://github.com/KhronosGroup/VK-GL-CTS/commit/28d433ac8ef5fdb437a9851c8f4a1159269f85fe
=> VulkanVideoSession: Increase MAX_BOUND_MEMORY

common/libs/VkCodecUtils/VulkanDeviceContext.cpp, common/libs/VkCodecUtils/VulkanDeviceContext.h
As the transfer queue can be different from the decode queue, this queue must be detected and associated to a valid number.
Fix typo in the name of the m_transferQueue member var.
=> VulkanDeviceContext: initialize transfer queue

vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH265.cpp
=> H265: Initialize profile_idc with INVALID value

vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH265.cpp
Use MAIN_10 profie for YUV420 and 10-bit input.
For others, use RANGE_EXTENSIONS profile.
Backport from https://github.com/nvpro-samples/vk_video_samples/pull/131
=> EncoderConfigH265: Use MAIN profile for YUV420 and 8-bit input.

vk_video_decoder/libs/VulkanVideoFrameBuffer/VulkanVideoFrameBuffer.cpp
Declare result only once and use the value
to decide to continue to initialize the image set.
=> decoder: fix unused variable warning

cmake/LinuxSettings.cmake, vk_video_decoder/libs/NvVideoParser/src/VulkanVP9Decoder.cpp
- [VulkanVP9Decoder: Fix 32b conversion errors](https://github.com/KhronosGroup/Vulkan-Video-Samples/commit/4248182a870fcc273e8fef03a1f86b15253b0b6f)
- [CMake: Add cast-qual to the cmake settings](https://github.com/KhronosGroup/Vulkan-Video-Samples/commit/bd9510b622d1f61ecd1e4925287503a8afa57049)
Reviewed in https://github.com/nvpro-samples/vk_video_samples/pull/150
=> vp9 compilation fix

cmake/LinuxSettings.cmake
This reverts commit 2409496dd82c9ed79501a2d1af32624874b1b19e.
This commit introduces a regression with warnings due to missing patches such as:
- 88875e4 common: Code compilation fixes
- 16607fe encoder: Deal with the Vulkan chained stuctures
`common: Code compilation fixes` needs #53 first to be backported properly
=> Revert "CMake: Add cast-qual to the cmake settings"

.github/workflows/main.yml, cmake/LinuxSettings.cmake
To validate potential issue when cross building VVS.
This is a configuration which can happen in CTS.
Fixing #73
=> ci: add a cross aarch64 job

vk_video_decoder/include/vkvideo_parser/VulkanVideoParserParams.h, vk_video_decoder/libs/NvVideoParser/src/VulkanAV1Decoder.cpp, vk_video_decoder/libs/NvVideoParser/src/VulkanVP9Decoder.cpp, vk_video_decoder/libs/VkVideoDecoder/VkVideoDecoder.cpp, vk_video_decoder/libs/VkVideoParser/VulkanVideoParser.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigAV1.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderDpbAV1.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderDpbH265.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderDpbH265.h, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderAV1.cpp
Since the update of the vulkan-headers to v1.4.323, the build warns out a lot of signed/unsigned issues.
See https://github.com/KhronosGroup/Vulkan-Headers/commit/088a00d81d1fc30ff77aacf31485871aebec7cb2#diff-63533ad576f78ac25c721fd6dd83c6e4ff313f38e12b41c7263bda8de3b672d6R25
=> codec: fix signed/unsigned comparison warnings

vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH264.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH264.h
In order to use the baseline or main profile,
transform_8x8_mode_flag should not be set to true. Use the auto select which is more appropriate here.
In case ADAPTIVE_TRANSFORM_ENABLE is used, disable it and warn user that this option can not be used with baseline and main profile.
=> EncoderConfigH264: use ADAPTIVE_TRANSFORM_AUTOSELECT

common/libs/VkCodecUtils/DecoderConfig.h
Print an error and exit if the input filename
has not been specified.
Print an error if the video file is not valid and exit.
=> DecoderConfig: show help if no input specified
